---
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWNLINT

SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false

EXCLUDED_DIRECTORIES:
  - .git
  - .venv
  - venv
  - node_modules
  - htmlcov
  - megalinter-reports

COPYPASTE_JSCPD_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
