"""durable_governance"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column("access_class", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_access_cost_usd", sa.Float(), nullable=True),
        sa.Column("requires_paid_subscription", sa.Boolean(), nullable=False),
        sa.Column("requires_credit_purchase", sa.Boolean(), nullable=False),
        sa.Column("auto_billing_required", sa.Boolean(), nullable=False),
        sa.Column("programmatic_access", sa.Boolean(), nullable=False),
        sa.Column("production_eligibility", sa.Boolean(), nullable=False),
        sa.Column("terms_last_verified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_data_class", sa.String(length=32), nullable=False),
        sa.Column("request_limit", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    op.create_table(
        "system_state",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("stopped", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "models",
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
        ),
        sa.PrimaryKeyConstraint("provider_id", "model_id"),
    )
    op.create_table(
        "provider_health_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("circuit_state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_health_events_provider_id"),
        "provider_health_events",
        ["provider_id"],
        unique=False,
    )
    op.create_table(
        "provider_quota_states",
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("exhausted", sa.Boolean(), nullable=False),
        sa.Column("security_blocked", sa.Boolean(), nullable=False),
        sa.Column("blocked_until", sa.Float(), nullable=False),
        sa.Column("reset_at", sa.Float(), nullable=True),
        sa.Column("circuit_state", sa.String(length=16), nullable=False),
        sa.Column("probe_until", sa.Float(), nullable=False),
        sa.Column("failures", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
        ),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    op.create_table(
        "task_profiles",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("task_class", sa.String(length=64), nullable=False),
        sa.Column("required_capabilities", sa.JSON(), nullable=False),
        sa.Column("context_tokens_estimate", sa.Integer(), nullable=False),
        sa.Column("minimum_quality_score", sa.Float(), nullable=False),
        sa.Column("requires_grounding", sa.Boolean(), nullable=False),
        sa.Column("profile_source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["task_requests.id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    # Carry forward the last acknowledged stop/resume command from the legacy audit.
    op.execute("""INSERT INTO system_state (id, stopped)
        SELECT 'global', COALESCE((SELECT event_type = 'SYSTEM_STOP' FROM audit_events
        WHERE event_type IN ('SYSTEM_STOP', 'SYSTEM_RESUME')
        ORDER BY created_at DESC, id DESC LIMIT 1), false)""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_profiles")
    op.drop_table("provider_quota_states")
    op.drop_index(
        op.f("ix_provider_health_events_provider_id"), table_name="provider_health_events"
    )
    op.drop_table("provider_health_events")
    op.drop_table("models")
    op.drop_table("system_state")
    op.drop_table("providers")
    # ### end Alembic commands ###
