"""quality_and_performance"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalation_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["task_requests.id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "model_task_performance",
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("task_class", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("quality_failures", sa.Integer(), nullable=False),
        sa.Column("infra_failures", sa.Integer(), nullable=False),
        sa.Column("quota_failures", sa.Integer(), nullable=False),
        sa.Column("unverified", sa.Integer(), nullable=False),
        sa.Column("hallucination_events", sa.Integer(), nullable=False),
        sa.Column("quality_samples", sa.Integer(), nullable=False),
        sa.Column("quality_sum", sa.Float(), nullable=False),
        sa.Column("latency_sum_ms", sa.Float(), nullable=False),
        sa.Column("recent_quality", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id", "model_id"],
            ["models.provider_id", "models.model_id"],
        ),
        sa.PrimaryKeyConstraint("provider_id", "model_id", "task_class"),
    )
    op.create_table(
        "quality_reports",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("hard_reject", sa.Boolean(), nullable=False),
        sa.Column("verification_state", sa.String(length=32), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["routing_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quality_reports")
    op.drop_table("model_task_performance")
    op.drop_table("escalation_requests")
    # ### end Alembic commands ###
